Use `cancel-in-progress` instead of `styfle/cancel-workflow-action`.
Compare https://github.com/google/guava/pull/8542.

Aside from the reasons listed there, I wonder if this would have avoided a flaky(?) failure that I saw today on https://github.com/google/google-java-format/pull/1441:

```
Run styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
  with:
    access_token: ***
    ignore_sha: false
    all_but_latest: false
    force_cancel: false
{
  eventName: 'pull_request',
  sha: 'ca5f660437c7f1489d511540cf8c6d047ea0edcf',
  headSha: 'a160145b17ff487adfa4519b087472e3d328088d',
  branch: 'zizdep',
  owner: 'google',
  repo: 'google-java-format',
  GITHUB_RUN_ID: '31412633123'
}
Found token: yes
Error: self-signed certificate; if the root CA is installed locally, try running Node.js with --use-system-ca
```